packages:
  - apps/*
  - packages/*

allowBuilds:
  bufferutil: true
  esbuild: true
  sharp: true
  utf-8-validate: true
  workerd: true

ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false
