// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./components/Banner.vue')['default']
    ChooseEpisodes: typeof import('./components/anime/ChooseEpisodes.vue')['default']
    Episode: typeof import('./components/anime/Episode.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PlayBangumi: typeof import('./components/anime/PlayBangumi.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Playing: typeof import('./components/Playing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
  }

}
